/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe
// PeImpactAnalysisEvent struct for PeImpactAnalysisEvent
type PeImpactAnalysisEvent struct {
	AppName string `json:"appName,omitempty"`
	ContainerName string `json:"containerName,omitempty"`
	Domain string `json:"domain,omitempty"`
	EventId int64 `json:"eventId,omitempty"`
	EventName string `json:"eventName,omitempty"`
	EventTime int64 `json:"eventTime,omitempty"`
	EventType string `json:"eventType,omitempty"`
	MaxChildEventId int64 `json:"maxChildEventId,omitempty"`
	ParentEventId int64 `json:"parentEventId,omitempty"`
	UserAccountId string `json:"userAccountId,omitempty"`
	Username string `json:"username,omitempty"`
	AuthorName string `json:"authorName,omitempty"`
	AuthorUsername string `json:"authorUsername,omitempty"`
	Branch string `json:"branch,omitempty"`
	CommitId string `json:"commitId,omitempty"`
	CommitMsg string `json:"commitMsg,omitempty"`
	CommitUrl string `json:"commitUrl,omitempty"`
	PullRequestDestBranch string `json:"pullRequestDestBranch,omitempty"`
	PullRequestHtmlUrl string `json:"pullRequestHtmlUrl,omitempty"`
	PullRequestId string `json:"pullRequestId,omitempty"`
	PullRequestNumber string `json:"pullRequestNumber,omitempty"`
	PullRequestSourceBranch string `json:"pullRequestSourceBranch,omitempty"`
	RepoId string `json:"repoId,omitempty"`
	RepoName string `json:"repoName,omitempty"`
	RepoOwner string `json:"repoOwner,omitempty"`
	RepoProvider string `json:"repoProvider,omitempty"`
	RepoType string `json:"repoType,omitempty"`
	RepoUrl string `json:"repoUrl,omitempty"`
	WebhookEventId string `json:"webhookEventId,omitempty"`
	ArtifactId string `json:"artifactId,omitempty"`
	ArtifactShortId string `json:"artifactShortId,omitempty"`
	BuildId string `json:"buildId,omitempty"`
	BuildNum int64 `json:"buildNum,omitempty"`
	CustomReleaseVersion string `json:"customReleaseVersion,omitempty"`
	ReleaseVersion string `json:"releaseVersion,omitempty"`
	ControlRepoName string `json:"controlRepoName,omitempty"`
	EndTime int64 `json:"endTime,omitempty"`
	Environments []PeImpactAnalysisEnvironment `json:"environments,omitempty"`
	ImpactAnalysisId int64 `json:"impactAnalysisId,omitempty"`
	IsAutoDeploy bool `json:"isAutoDeploy,omitempty"`
	ModuleName string `json:"moduleName,omitempty"`
	Sha string `json:"sha,omitempty"`
	SourceBranch string `json:"sourceBranch,omitempty"`
	StartTime int64 `json:"startTime,omitempty"`
	State string `json:"state,omitempty"`
	EndTimeAsStr string `json:"endTime_asStr,omitempty"`
	IsAutoDeployAsStr string `json:"isAutoDeploy_asStr,omitempty"`
	StartTimeAsStr string `json:"startTime_asStr,omitempty"`
	ImpactAnalysisIdAsStr string `json:"impactAnalysisId_asStr,omitempty"`
	BuildNumAsStr string `json:"buildNum_asStr,omitempty"`
	EventTimeAsStr string `json:"eventTime_asStr,omitempty"`
	EventIdAsStr string `json:"eventId_asStr,omitempty"`
	MaxChildEventIdAsStr string `json:"maxChildEventId_asStr,omitempty"`
	ParentEventIdAsStr string `json:"parentEventId_asStr,omitempty"`
}
