/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe

// PuppetEnterpriseCredentialsWithToken Puppet Enterprise credentials with token
type PuppetEnterpriseCredentialsWithToken struct {
	Domain                     string `json:"domain,omitempty"`
	Name                       string `json:"name,omitempty"`
	Certificate                string `json:"certificate,omitempty"`
	CodeManagerEndpoint        string `json:"codeManagerEndpoint,omitempty"`
	NodeClassifierEndpoint     string `json:"nodeClassifierEndpoint,omitempty"`
	OrchestratorEndpoint       string `json:"orchestratorEndpoint,omitempty"`
	PuppetDBEndpoint           string `json:"puppetDBEndpoint,omitempty"`
	PuppetServerEndpoint       string `json:"puppetServerEndpoint,omitempty"`
	PuppetServerCertificate    string `json:"puppetServerCertificate,omitempty"`
	PuppetServerPrivateKey     string `json:"puppetServerPrivateKey,omitempty"`
	UseLegacyCompileEndpoint   bool   `json:"useLegacyCompileEndpoint,omitempty"`
	ProtectedEnvironmentsCount int32  `json:"protectedEnvironmentsCount,omitempty"`
	Token                      string `json:"token,omitempty"`
	TokenExpiration            int64  `json:"tokenExpiration,omitempty"`
}
