/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe

// EvaluatePermissionsRequest struct for EvaluatePermissionsRequest
type EvaluatePermissionsRequest struct {
	Token       int64               `json:"token,omitempty"`
	Permissions []PermissionTriplet `json:"permissions,omitempty"`
}
