/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe
// CreateTokenRequest struct for CreateTokenRequest
type CreateTokenRequest struct {
	Email string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
}
