/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe

// CurrentUserDetails struct for CurrentUserDetails
type CurrentUserDetails struct {
	User       User        `json:"user,omitempty"`
	Workspaces []Workspace `json:"workspaces,omitempty"`
}
