/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe
// Repository struct for Repository
type Repository struct {
	DisplayName string `json:"displayName,omitempty"`
	DisplayOwner string `json:"displayOwner,omitempty"`
	Name string `json:"name,omitempty"`
	Owner string `json:"owner,omitempty"`
	Project string `json:"project,omitempty"`
	Provider string `json:"provider,omitempty"`
	RepositoryId string `json:"repositoryId,omitempty"`
	WebhookId string `json:"webhookId,omitempty"`
}
