/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe

// Workspace struct for Workspace
type Workspace struct {
	Domain string `json:"domain"`
	Name   string `json:"name"`
}
