/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe
// PuppetEnterpriseCredentialsId struct for PuppetEnterpriseCredentialsId
type PuppetEnterpriseCredentialsId struct {
	Domain string `json:"domain,omitempty"`
	Name string `json:"name,omitempty"`
}
