/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe

// Permitted List of entries of whether user has corresponding permission
type Permitted struct {
	// List of results for requested permissions
	Results []bool `json:"results"`
}
