/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe
// LoginDataCcexpires struct for LoginDataCcexpires
type LoginDataCcexpires struct {
	Year int32 `json:"year,omitempty"`
	Month string `json:"month,omitempty"`
	LeapYear bool `json:"leapYear,omitempty"`
	MonthValue int32 `json:"monthValue,omitempty"`
}
