/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe

// User struct for User
type User struct {
	Domain        string `json:"domain,omitempty"`
	Id            int64  `json:"id,omitempty"`
	FirstName     string `json:"firstName,omitempty"`
	LastName      string `json:"lastName,omitempty"`
	UserName      string `json:"userName,omitempty"`
	Email         string `json:"email,omitempty"`
	CreatedTime   int64  `json:"createdTime,omitempty"`
	CompanyName   string `json:"companyName,omitempty"`
	GravatarEmail string `json:"gravatarEmail,omitempty"`
	RootUser      bool   `json:"rootUser,omitempty"`
	SuperUser     bool   `json:"superUser,omitempty"`
}
