/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe
// ContainerBuildConfiguration struct for ContainerBuildConfiguration
type ContainerBuildConfiguration struct {
	BuildCapabilities []string `json:"buildCapabilities,omitempty"`
	BuildVars []string `json:"buildVars,omitempty"`
	DockerFilePath string `json:"dockerFilePath,omitempty"`
	NoDind bool `json:"noDind,omitempty"`
	ServerDomain string `json:"serverDomain,omitempty"`
	VmArgs []string `json:"vmArgs,omitempty"`
	VmImage string `json:"vmImage,omitempty"`
	VmProvider string `json:"vmProvider,omitempty"`
	VmPull bool `json:"vmPull,omitempty"`
	NoDindAsStr string `json:"noDind_asStr,omitempty"`
	VmPullAsStr string `json:"vmPull_asStr,omitempty"`
}
