/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe
// PeImpactAnalysisEnvironment struct for PeImpactAnalysisEnvironment
type PeImpactAnalysisEnvironment struct {
	DeploymentType string `json:"deploymentType,omitempty"`
	ModuleImpactAnalysisControlRepoId ControlRepoId `json:"moduleImpactAnalysisControlRepoId,omitempty"`
	NodeGroupId string `json:"nodeGroupId,omitempty"`
	PeCredentialsId PuppetEnterpriseCredentialsId `json:"peCredentialsId,omitempty"`
	PipelineDestinationId string `json:"pipelineDestinationId,omitempty"`
}
