/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe
// LoginData struct for LoginData
type LoginData struct {
	Domain string `json:"domain,omitempty"`
	Name string `json:"name,omitempty"`
	Country string `json:"country,omitempty"`
	HashKey string `json:"hashKey,omitempty"`
	RangeKey string `json:"rangeKey,omitempty"`
	PasswordHash string `json:"passwordHash,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	UserId string `json:"userId,omitempty"`
	AccountId string `json:"accountId,omitempty"`
	EmailVerificationState string `json:"emailVerificationState,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	LastName string `json:"lastName,omitempty"`
	CompanyName string `json:"companyName,omitempty"`
	CreateTime int64 `json:"createTime,omitempty"`
	LoginState string `json:"loginState,omitempty"`
	WorkspaceName string `json:"workspaceName,omitempty"`
	IsWorkspace bool `json:"isWorkspace,omitempty"`
	Workspace bool `json:"workspace,omitempty"`
	HashKeyName string `json:"hashKeyName,omitempty"`
	RangeKeyName string `json:"rangeKeyName,omitempty"`
	PrivateRepoCount int32 `json:"privateRepoCount,omitempty"`
	MaxPrivateRepoCount int32 `json:"maxPrivateRepoCount,omitempty"`
	MaxProjectCount int32 `json:"maxProjectCount,omitempty"`
	MaxNodeCount int32 `json:"maxNodeCount,omitempty"`
	PlanExpiration int64 `json:"planExpiration,omitempty"`
	MaxTeamCount int32 `json:"maxTeamCount,omitempty"`
	PlanName string `json:"planName,omitempty"`
	LdapDN string `json:"ldapDN,omitempty"`
	LastLoginTime int64 `json:"lastLoginTime,omitempty"`
	GravatarEmail string `json:"gravatarEmail,omitempty"`
	PaymentFailed string `json:"paymentFailed,omitempty"`
	Ccexpires LoginDataCcexpires `json:"ccexpires,omitempty"`
	DefaultProductType string `json:"defaultProductType,omitempty"`
	StripeCustomerId string `json:"stripeCustomerId,omitempty"`
	StripeSubscriptionId string `json:"stripeSubscriptionId,omitempty"`
	LoginStateCodeId string `json:"loginStateCodeId,omitempty"`
	SuccessLogins []string `json:"successLogins,omitempty"`
	SuccessLoginsMaybeNull []string `json:"successLoginsMaybeNull,omitempty"`
	EmailVerificationStateCodeId string `json:"emailVerificationStateCodeId,omitempty"`
	ResetPasswordKey []string `json:"resetPasswordKey,omitempty"`
	NicknameLower string `json:"nicknameLower,omitempty"`
	LastFailedLoginTime int64 `json:"lastFailedLoginTime,omitempty"`
	FailedLoginCount int32 `json:"failedLoginCount,omitempty"`
	Ddbccexpires string `json:"ddbccexpires,omitempty"`
	SelectedWorkspace string `json:"selectedWorkspace,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
}
