/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe

// ListPeIntegrationsWithTokenResponse List integrated PE instances
type ListPeIntegrationsWithTokenResponse struct {
	// List of PE integrations (including the token)
	PeIntegrations []PuppetEnterpriseCredentialsWithToken `json:"peIntegrations"`
}
