/*
 * CD4PE API V1
 *
 * API for CD4PE V1
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cd4pe

// PermissionTriplet struct for PermissionTriplet
type PermissionTriplet struct {
	ObjectType string `json:"object_type"`
	Action     string `json:"action"`
	Instance   string `json:"instance"`
}
